const mongoose = require("mongoose");
const Schema = mongoose.Schema;
const projectSchema = new Schema({
  projectName: String,
  link: String,
  description: String,
  duration: String
});
const resumesSchema = new Schema({
  name: String,
  roll_no: String,
  contact: String,
  email: String,
  degree_name: String,
  CGPA: String,
  Duration: String,
  University_Name: String,
  board_12: String,
  per_12: String,
  pass_12: String,
  school_12: String,
  board_10: String,
  per_10: String,
  pass_10: String,
  school_10: String,
  lang_1: String,
  lang_2: String,
  lang_3: String,
  lang_4: String,
  lang_5: String,
  lang_6: String,
  lang_7: String,
  lang_8: String,
  proj_1: String,
  proj_2: String,
  proj_3: String,
  projd_1: String,
  projd_2: String,
  projd_3: String,
  plink_1: String,
  plink_2: String,
  plink_3: String,
  ach_1: String,
  ach_2: String,
  ach_3: String,
  ach_4: String,
  ach_5: String,
  hob_1: String,
  hob_2: String,
  hob_3: String,
  link_1: String,
  link_2: String,
  link_3: String,
  link_4: String,
  hlink_1: String,
  hlink_2: String,
  hlink_3: String,
  hlink_4: String,
  work_projects:[projectSchema],
  author: {
    googleId: String,
    name: String,
  },
});

module.exports = mongoose.model("Resumes", resumesSchema);
